### ISSUE TITLE
Extra deploy

### ISSUE THREAD

**Issue by gulecroc** [docker-mailserver/docker-mailserver-helm#115]
Hi,

I would like to deploy extra resources, like logging configuration with kube-logging (it was the purpose of https://github.com/docker-mailserver/docker-mailserver-helm/issues/83)

Bitnami, who maintained large charts, use a "simple" way to achieve this :

- add `extraDeploy` to values : https://github.com/bitnami/charts/blob/9ee59719f5345c44255886264cba57cc82867b19/template/CHART_NAME/values.yaml#L58
- add `extra-list.yaml` file : https://github.com/bitnami/charts/blob/main/template/CHART_NAME/templates/extra-list.yaml

What do you think ?

Best regards,
Guillaume

**Comment by cfis** [comment]
Do you have example of how you would use this?

**Comment by gulecroc** [comment]
For exemple to add kube-logging Flow :

values :
```
# values used in extraDeploy
logging:
  cluster: demo

# extraDeploy values
extraDeploy:
  - apiVersion: logging.banzaicloud.io/v1beta1
    kind: Flow
    metadata:
      labels:
        app.kubernetes.io/name: '{{ template "dockermailserver.fullname" . }}'
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
      name: logging-flow-docker-mailserver-postfix-qmgr
    spec:
      filters:
        - dedot:
            de_dot_nested: true
            de_dot_separator: '-'
        - grep:
            regexp:
              - key: log
                pattern: /.+ postfix\/qmgr\u005B[0-9]+\u005D\u003A [0-9A-F]+\u003A from=/
        - record_modifier:
            records:
              - cluster:  '{{ .Values.logging.cluster }}'
              - service: "postfix/qmgr"
              - time: ${require 'time'; Time.parse(record['time'].to_s).utc.iso8601(3)}
              - postfix_time: ${record['log'].match(/([A-Za-z]{3}[ ]{1,2}[0-9]{1,2} [0-9]{2}\:[0-9]{2}\:[0-9]{2}) /).captures[0]}
              - log: ${record['log'].gsub(/\n/, '')}          
        - record_modifier:
            records:
              - postfix_time: ${require 'time'; Time.parse(record['postfix_time']).utc.iso8601(3)}
              - time: ${require 'time'; Time.parse(record['postfix_time']).utc.iso8601(3)}         
              - hostname:  ${record['log'].match(/.+ (.+) postfix\/qmgr\u005B/).captures[0]}
              - process: ${record['log'].match(/.+ (postfix\/qmgr\u005B[0-9]+\u005D)/).captures[0]}
              - queue_id: ${record['log'].match(/postfix\/qmgr\u005B[0-9]+\u005D\u003A ([0-9A-F]+)\u003A from=/).captures[0]}
              - from:  ${record['log'].match(/postfix\/qmgr\u005B[0-9]+\u005D\u003A [0-9A-F]+\u003A from=<([^<>]+)>,/).captures[0]}
              - domain: ${record['log'].match(/.+ from=<[^@<]+@([^@>]+)>,/).captures[0]}
              - size: ${record['log'].match(/.+, size=([0-9]+), nrcpt=/).captures[0]}
              - nrcpt: ${record['log'].match(/.+, nrcpt=([0-9]+) \(queue active\)/).captures[0]}
      globalOutputRefs:
        - logging-output-opensearch-postfix
      match:
        - select:
            container_names:
              - dockermailserver
```

will generate in the extra-list.yaml :

```
---
# Source: docker-mailserver/templates/extra-list.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  labels:
    app.kubernetes.io/name: 'smtp-docker-mailserver'
    chart: 'docker-mailserver-3.0.10'
    heritage: 'Helm'
    release: 'smtp'
  name: logging-flow-postfix-qmgr-k8s
spec:
  filters:
  - dedot:
      de_dot_nested: true
      de_dot_separator: '-'
  - grep:
      regexp:
      - key: log
        pattern: /.+ postfix\/qmgr\u005B[0-9]+\u005D\u003A [0-9A-F]+\u003A from=/
  - record_modifier:
      records:
      - cluster: 'demo'
      - service: postfix/qmgr
      - time: ${require 'time'; Time.parse(record['time'].to_s).utc.iso8601(3)}
      - postfix_time: ${record['log'].match(/([A-Za-z]{3}[ ]{1,2}[0-9]{1,2} [0-9]{2}\:[0-9]{2}\:[0-9]{2})
          /).captures[0]}
      - log: ${record['log'].gsub(/\n/, '')}
  - record_modifier:
      records:
      - postfix_time: ${require 'time'; Time.parse(record['postfix_time']).utc.iso8601(3)}
      - time: ${require 'time'; Time.parse(record['postfix_time']).utc.iso8601(3)}
      - hostname: ${record['log'].match(/.+ (.+) postfix\/qmgr\u005B/).captures[0]}
      - process: ${record['log'].match(/.+ (postfix\/qmgr\u005B[0-9]+\u005D)/).captures[0]}
      - queue_id: ${record['log'].match(/postfix\/qmgr\u005B[0-9]+\u005D\u003A ([0-9A-F]+)\u003A
          from=/).captures[0]}
      - from: ${record['log'].match(/postfix\/qmgr\u005B[0-9]+\u005D\u003A [0-9A-F]+\u003A
          from=<([^<>]+)>,/).captures[0]}
      - domain: ${record['log'].match(/.+ from=<[^@<]+@([^@>]+)>,/).captures[0]}
      - size: ${record['log'].match(/.+, size=([0-9]+), nrcpt=/).captures[0]}
      - nrcpt: ${record['log'].match(/.+, nrcpt=([0-9]+) \(queue active\)/).captures[0]}
  globalOutputRefs:
  - logging-output-opensearch-postfix
  match:
  - select:
      container_names:
      - dockermailserver
```

And I you can see helm templating works
