### ISSUE TITLE
[FEATURE] Add subPath to volumeMounts for main Deployment

### ISSUE THREAD

**Issue by marcopaggioro** [docker-mailserver/docker-mailserver-helm#146]
Hi, 
I would like to use a single pre-created pvc to manage all the folders required by the container. 
However, this requires me to define the subPaths of the volumeMounts.

From deployment.yaml
```
 # Mount Volumes
{{- range $name, $persistence := .Values.persistence }}
  {{- if $persistence.enabled }}
    - name: {{ $name }}
      mountPath: {{ $persistence.mountPath }}
  {{- end }}
{{- end }}
```

Maybe something like
```
 # Mount Volumes
{{- range $name, $persistence := .Values.persistence }}
  {{- if $persistence.enabled }}
    - name: {{ $name }}
      mountPath: {{ $persistence.mountPath }}
      subPath: {{ $persistence.subPath}}
  {{- end }}
{{- end }}
```
and then in custom-values.yaml
```
persistence:
  mail-config:
    existingClaim: mail-server-pvc
    subpath: config
 mail-data:
    existingClaim: mail-server-pvc
    subpath: data
... and so on
```
