### ISSUE TITLE
Can not use the same PVC for all persistence nodes

### ISSUE THREAD

**Issue by marcopaggioro** [docker-mailserver/docker-mailserver-helm#148]
The desired is to use a single PVC for the entire persistence of the container and use the subPaths to "sort" the content into subfolders.

Configuring the helm like this:
```
persistence:
  mail-config:
    existingClaim: mail-server-pvc
    subPath: config
  mail-data:
    existingClaim: mail-server-pvc
    subPath: data
```

You get a pod with the infinite "Pending" status. This is because the generated Deployment contains two volumes that point to the same PVC:
```
volumes:
  - name: mail-config
    persistentVolumeClaim:
      claimName: mail-server-pvc
  - name: mail-data
    persistentVolumeClaim:
      claimName: mail-server-pvc
.....
volumeMounts:
  - name: mail-config
    mountPath: /tmp/docker-mailserver
    subPath: config
  - name: mail-data
    mountPath: /var/mail
    subPath: data
```

The Kubernetes controller interprets these two definitions as two separate requests to mount the same PVC, leading to conflicts in the volume attach.

If I put only one volume the pod starts:
```
volumes:
  - name: mail-storage
    persistentVolumeClaim:
      claimName: mail-server-pvc
  .....
volumeMounts:
  - name: mail-storage
    mountPath: /tmp/docker-mailserver
    subPath: config
  - name: mail-storage
    mountPath: /var/mail
    subPath: data
```

So it seems like a problem in defining a more than one volume with different name that points to the same PVC (despite the PVC being ReadWriteMany and in Bound state). I guess a PVC can be attached to multiple pods but not multiple times to the same pod.

I don't have a possible solution in mind yet without revolutionizing everything but I'll think about it!

### Workaround
Disable all persistence voices and add the volume in extraVolumes and repeat all volumeMounts (mail-config, mail-data etc) in extraVolumesMounts
```
persistence:
  mail-config:
    enabled: false
  mail-data:
    enabled: false
  mail-state:
    enabled: false
  mail-log:
    enabled: false

deployment:
  extraVolumes:
    - name: storage
      persistentVolumeClaim:
        claimName: mail-server-pvc
  extraVolumeMounts:
    - name: storage
      mountPath: /tmp/docker-mailserver
      subPath: config
    - name: storage
      mountPath: /var/mail
      subPath: mail
    - name: storage
      mountPath: /var/mail-state
      subPath: state
    - name: storage
      mountPath: /var/log/mail
      subPath: log
```
