### ISSUE TITLE
only works in "demo mode", chart fails when setting any other option

### ISSUE THREAD

**Issue by chkp-amirtal** [docker-mailserver/docker-mailserver-helm#27]
❯ helm3 install mailserver . -f values-used.yaml --namespace utils --debug
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /Users/amirtal/git/terraform-cluster-shared-prod/tfiaas/kops/kubernetes-helm/docker-mailserver

**Error: YAML parse error on docker-mailserver/templates/configmap.yaml: error converting YAML to JSON: yaml: line 59: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 59: did not find expected key**
YAML parse error on docker-mailserver/templates/configmap.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/private/tmp/helm-20200619-73670-pk36oo/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/private/tmp/helm-20200619-73670-pk36oo/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/private/tmp/helm-20200619-73670-pk36oo/pkg/action/action.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
	/private/tmp/helm-20200619-73670-pk36oo/pkg/action/install.go:238
main.runInstall
	/private/tmp/helm-20200619-73670-pk36oo/cmd/helm/install.go:229
main.newInstallCmd.func1
	/private/tmp/helm-20200619-73670-pk36oo/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20200619-73670-pk36oo/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20200619-73670-pk36oo/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20200619-73670-pk36oo/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20200619-73670-pk36oo/cmd/helm/helm.go:83
runtime.main
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/asm_amd64.s:1373

**Comment by dfoxg** [comment]
@amirtal-cp In the meantime, were you able to work around the error?

**Comment by chkp-amirtal** [comment]
> @amirtal-cp In the meantime, were you able to work around the error?

deployed using YAML manifest instead of using helm chart.

**Comment by dfoxg** [comment]
Can you maybe share your used templates?

**Comment by chkp-amirtal** [comment]
don't really have it in use any more, it was used for testing.

you can use:
```
helm3 repo add geek-cookbook https://geek-cookbook.github.io/charts
helm3 template -n mail-server docker-mailserver geek-cookbook/docker-mailserver > /tmp/manifest.yaml
```
and edit the generated YAML as needed.

**Comment by desmo999r** [comment]
ran into that issue as well.
I think it's because `templates/configmap.yaml` is trying to include the files `config/opendkim/*` and it cannot find them:
`  {{- (.Files.Glob "config/opendkim/*").AsConfig | nindent 2 }}`
then when `templates/configmap.yaml` is rendered it spits `{}` which is not valid YAML.

Here is what the rendered `templates/configmap.yaml` looks like:


```
# Source: docker-mailserver/templates/configmap.yaml
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app.kubernetes.io/name: RELEASE-NAME-docker-mailserver
    chart: "docker-mailserver-1.0.1"
    heritage: "Helm"
    release: "RELEASE-NAME"
  name: RELEASE-NAME-docker-mailserver-configs
data:
  
  dovecot.cf: |
    # File for additional dovecot configurations.
    # For more informations read http://wiki.dovecot.org/BasicConfiguration
  
    #mail_max_userip_connections = 50
  fail2ban-fail2ban.cf: |
    [Definition]
  
    # Option: loglevel
    # Notes.: Set the log level output.
    #         CRITICAL
    #         ERROR
    #         WARNING
    #         NOTICE
    #         INFO
    #         DEBUG
    # Values: [ LEVEL ]  Default: ERROR
    #
  
    # loglevel = INFO
  
    # Options: dbpurgeage
    # Notes.: Sets age at which bans should be purged from the database
    # Values: [ SECONDS ] Default: 86400 (24hours), 604800 (1week)
    # dbpurgeage = 604800
  fail2ban-jail.cf: |
    [DEFAULT]
  
    # "bantime" is the number of seconds that a host is banned.
    #bantime  = 10800
  
    # A host is banned if it has generated "maxretry" during the last "findtime"
    # seconds.
    #findtime  = 600
  
    # "maxretry" is the number of failures before a host get banned.
    #maxretry = 3
  fetchmail.cf: "## Example configuration: IMAP\n#poll imap.example.com with proto IMAP\n#\tuser 'username' there with\n#\tpassword 'secret'\n#\tis 'user1@domain.tld'\n#\there ssl\n\n## Example configuration: POP3\n#poll pop3.example.com with proto POP3\n#\tuser 'username' there with\n#\tpassword 'secret'\n#\tis 'user2@domain.tld'\n#\there options keep ssl\n"
  postfix-accounts.cf: ""
  postfix-aliases.cf: ""
  postfix-main.cf: ""
  postfix-master.cf: ""
  postfix-virtual.cf: ""
  spamassassin-rules.cf: ""
  {}
  postfix-main.cf: |
...  
```
see the `{}` right after `spamassassin-rules.cf: ""`.

If I remove the line 30 from `templates/configmap.yaml` it works perfectly.
```
{{- (.Files.Glob "config/opendkim/*").AsConfig | nindent 2 }}
```
