### ISSUE TITLE
YAML parse error

### ISSUE THREAD

**Issue by emouawad** [docker-mailserver/docker-mailserver-helm#99]
```cmd
Error: YAML parse error on docker-mailserver/templates/service.yaml: error converting YAML to JSON: yaml: line 49: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 49: mapping values are not allowed in this context
YAML parse error on docker-mailserver/templates/service.yaml
```

Chart  version 3.0.4

when setting publicIp >> FAIL
```yaml
service:
  type: LoadBalancer
  loadBalancer:
    publicIp: "xx.xx.xx.xx"
 ```

remove >> SUCCESS
```yaml
service:
  type: LoadBalancer
 ```    
 
 
 ALSO SAME ERROR
 
 ```yaml
 metrics:
  enabled: true
 ```

**Comment by cfis** [comment]
Thanks for the report. I see the error with loadbalancer but not metrics. 

If you still see it, can you look at the generated yaml and see what the issue is?

```
helm template --debug --repo https://docker-mailserver.github.io/docker-mailserver-helm docker-mailserver --namespace docker-mailserver  --values <path to your values file> helm.yaml

**Comment by emouawad** [comment]
Thanks loadBalancer publicIp issue fixed.

Enabling Metrics issue still happening - looks the volume mount: 
mail and mail-state are mounted under the same name: data

```log
client.go:428: [debug] error updating the resource "mailserver-docker-mailserver":
         cannot patch "mailserver-docker-mailserver" with kind Deployment: Deployment.apps "mailserver-docker-mailserver" is invalid: [spec.template.spec.containers[1].volumeMounts[0].name: Not found: "data", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "data"]
upgrade.go:434: [debug] warning: Upgrade "mailserver" failed: cannot patch "mailserver-docker-mailserver" with kind Deployment: Deployment.apps "mailserver-docker-mailserver" is invalid: [spec.template.spec.containers[1].volumeMounts[0].name: Not found: "data", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "data"]
Error: UPGRADE FAILED: cannot patch "mailserver-docker-mailserver" with kind Deployment: Deployment.apps "mailserver-docker-mailserver" is invalid: [spec.template.spec.containers[1].volumeMounts[0].name: Not found: "data", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "data"]
helm.go:84: [debug] cannot patch "mailserver-docker-mailserver" with kind Deployment: Deployment.apps "mailserver-docker-mailserver" is invalid: [spec.template.spec.containers[1].volumeMounts[0].name: Not found: "data", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "data"]
```


```yaml
        - name: metrics-exporter
          image: blackflysolutions/postfix-exporter@sha256:7ed7c0534112aff5b44757ae84a206bf659171631edfc325c3c1638d78e74f73
          imagePullPolicy: IfNotPresent
          command: ["/bin/postfix_exporter"]
          args: 
            - "--postfix.showq_path"
            - "/var/mail-state/spool-postfix/public/showq"
            - "--postfix.logfile_path"
            - "/var/log/mail/mail.log"

          ports:
            - containerPort: 9154
              name: http
              protocol: TCP
          resources:
            requests:
              memory: 256Mi          
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false

          volumeMounts:
            - name: data
              mountPath: /var/log/mail
              subPath: log
              readOnly: true     
            - name: data
              mountPath: /var/mail-state
              subPath: mail-state
              readOnly: true
```
